# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  netcoremediator:
    image: netcoremediator
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 5444:5444

  postgres:
    image: postgres
    volumes:
      - thc_postgres_data:/var/lib/postgresql/data
    ports:
      - 5423:5432
    environment:
      POSTGRES_DB: cedriko
      POSTGRES_USER: cedriko
      POSTGRES_PASSWORD: cedriko_pwd

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@thc.com
      PGADMIN_DEFAULT_PASSWORD: test

volumes:
  thc_postgres_data:
